version: '2'

networks:
  core_network:
    #enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.128.0.0/24
          gateway: 10.128.0.1
        # - subnet: 200 networks:1:1001:26::/64
        #   gateway: 2001:1001:26::1

services:
  mme:
     build: ./
     container_name: mme
     hostname: mme
     entrypoint:
      - "/bin/sh"
      - "/usr/local/etc/run_mme.sh"
     volumes:
      - "./config:/usr/local/etc:z"
      - "./var:/usr/local/var:z"
     privileged: true
     networks:
       core_network:
         ipv4_address: 10.128.0.20

  sgw:
     build: ./
     container_name: sgw
     hostname: sgw
     entrypoint:
      - "/bin/sh"
      - "/usr/local/etc/run_sgw.sh"
     volumes:
      - "./config:/usr/local/etc:z"
      - "./var:/usr/local/var:z"
     privileged: true
     networks:
       core_network:
         ipv4_address: 10.128.0.21

  pgw:
     build: ./
     container_name: pgw
     hostname: pgw
     entrypoint:
      - "/bin/sh"
      - "/usr/local/etc/run_pgw.sh"
     volumes:
      - "./config:/usr/local/etc:z"
      - "./var:/usr/local/var:z"
     cap_add:
       -  NET_ADMIN
     devices:
       -  /dev/net/tun
     networks:
       core_network:
         ipv4_address: 10.128.0.22

  pcrf:
    build: ./
    container_name: pcrf
    hostname: pcrf
    entrypoint:
      - "/bin/sh"
      - "/usr/local/etc/run_pcrf.sh"
    volumes:
      - "./config:/usr/local/etc:z"
      - "./var:/usr/local/var:z"
    networks:
       core_network:
         ipv4_address: 10.128.0.23

  enb:
    build: ./srsLTE-fauxRF
    container_name: enb
    depends_on:
      - mme
    ipc: shareable 
    cap_add:
      - SYS_NICE
    networks:
      core_network:
         ipv4_address: 10.128.0.24
    volumes:
      - ./srsLTE-fauxRF/run_enb.sh:/root/run_enb.sh:z
    entrypoint:
      - /bin/sh
      - /root/run_enb.sh

  ue:
    container_name: ue
    build: ./srsLTE-fauxRF
    ipc: "container:enb"
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    devices:
      - /dev/net/tun
    network_mode: "none"
    depends_on:
      - enb
    volumes:
      - ./srsLTE-fauxRF/run_ue.sh:/root/run_ue.sh:z
    entrypoint:
      - /bin/sh
      - /root/run_ue.sh



