version: '2'

volumes:
 mongodb_data:

networks:
  core_network:
    #enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.128.0.0/24
          gateway: 10.128.0.1
        # - subnet: 200 networks:1:1001:26::/64
        #   gateway: 2001:1001:26::1

services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    volumes:
      - mongodb_data:/data/db
    hostname: mongodb
    networks:
      core_network:
        ipv4_address: 10.128.0.15

  webui:
    build: ./
    depends_on:
      - mongodb
    environment:
      - DB_URI=mongodb://mongodb/open5gs
    container_name: webui
    hostname: webui
    ports:
      - "3000:3000"
    volumes:
        - "./config:/usr/local/etc:z"
    entrypoint:
      - "/bin/sh"
      - "/usr/local/etc/run_webui.sh"
    networks:
      core_network:
        ipv4_address: 10.128.0.16

  mongodbloader:
    image: mongo:latest
    depends_on:
      - webui
    environment:
      - DB_HOST=mongodb
    volumes:
      - "./provisioning/db/run_db.sh:/tmp/run.sh:z"
      - "./provisioning/db/imsi1.json:/tmp/imsi1.json:z"
    entrypoint:
      - /bin/sh
      - /tmp/run.sh
    networks:
      core_network:
        ipv4_address: 10.128.0.17

  hss:
    build: ./
    depends_on:
      - mongodb
    container_name: hss
    hostname: hss
    entrypoint:
      - "/bin/sh"
      - "/usr/local/etc/run_hss.sh"
    volumes:
      - "./config:/usr/local/etc:z"
      - "./var:/usr/local/var:z"
    privileged: true
    networks:
      core_network:
        ipv4_address: 10.128.0.18
