db_uri: mongodb://10.128.0.15/open5gs

logger:
    file: /usr/local/var/log/open5gs/hss.log
    trace: 
        app: 1
        diameter: 1

parameter:

hss:
    freeDiameter: /usr/local/etc/freeDiameter/hss.conf
