logger:
    file: /usr/local/var/log/open5gs/sgw.log
    trace: 
        app: 1
        gtpv2: 1
        gtp: 1

parameter:
    no_ipv6: true

sgw:
    gtpc:
      addr: 10.128.0.21
    gtpu:
      addr: 10.128.0.21
